cboard-org/cboard-api

api/models/User.js

Update password check

---

api/mail/index.js
app.yml

update sendgrid info

---

.prettierrc
README.md
api/swagger/swagger.yaml
app.js

Some initial edits to the readme.
There was nothing about running mongod before, but there's connection errors without it.
I also find it duplicative to include a lot of the general cboard info. I figured a summary and a link back to the main repo will suffice.
PS i tend to prefer single quotes, but it appears prettier enforces double?

readme edits

---

.env.sample
.gitignore
app.js
package-lock.json
package.json

Hi, @martinbedouret.
I hope you don't mind, but I installed two packages to make it easy to develop the API.
`nodemon`: So when changes are made on the files, the server restarts automatically.
`dotenv`: So we can define some of the `process.env` variables in a cleaner way.
PS: The other changes were made by Prettier.

Improving development environment

---

api/controllers/user.js
api/models/User.js
api/swagger/swagger.yaml
test/controllers/board.js
test/controllers/user.js
test/helper.js

#137 was merged too soon. Reverting so we can review the changes properly.

Revert "Fix vulnerability with updateUser route"

---

package.json
test/controllers/analytics.js
test/controllers/media.js
test/controllers/user.js
test/helper.js

This PR updates or skips several tests that are currently failing on the master branch. It also updates to a version of swagger-node that returns the exit code 1 on failure rather than 0, which currently causes CircleCI to think that tests have passed even though there are failures.
There hasn't been a release since the fix to swagger-node so I had to pin the version by commit.

Fix broken tests on master branch

---

app.js
package.json

close #205 
Needs to add the env APPINSIGHTS_INSTRUMENTATIONKEY to the production variables

Add application insights

---

api/controllers/location.js
api/controllers/user.js
api/helpers/localize.js
api/models/User.js
api/passport/facebook.js
api/passport/facebookToken.js
api/passport/google.js
api/passport/googleToken.js
api/swagger/swagger.yaml
app.js
package.json
test/controllers/location.js
test/helper.js
test/postman/cboard-api.postman_collection.json

Feature - Get user location

---

api/mail/email-verification.js

`verifySendMailCallback` was already declared line 76

remove duplicated `verifySendMailCallback` declaration

---

app.js
test/controllers/user.js
test/postman/cboard-api.postman_collection.json

this PR solves an actual break of the app after receiving a request on an admin's endpoint with user Auth.
close #224

Solve App stop after receiving a request on a admin's endpoint with user Auth

---

api/controllers/subscriber.js
api/models/Subscribers.js
package.json
test/controllers/subscriber.js
test/helper.js

Integrate purchases subscriptionsV2

---

test/controllers/location.js
test/helper.js

use constant IP on location test

---

api/models/User.js
test/controllers/user.js

Add createdAt property for users

---

api/models/Subscribers.js

Delete unique prop from country on subscriber schema definition

---

api/controllers/user.js
api/models/Subscribers.js

Retrieve subscriber on login

---

config/env/development.js
config/env/production.js
package.json
yarn.lock

See [Smtp Nodemailer Docs](https://nodemailer.com/smtp/) and [TLS errors](https://github.com/nodemailer/nodemailer#i-get-tls-errors)

Update for Twilio SendGrid

---

api/controllers/analytics.js

Google analytics API auth before batchGet

---

api/controllers/subscriber.js

Fix function that verify if subscription is active for another user

Fix use of setSubscriptionState on checkIfAppStoreTransactionIsValid

---

config/env/development.js

Change development databaseUrl from localhost to 127.0.0.1

---

api/models/Subscribers.js

Handle 410 error code (gone)  retrieved from android publisher

---

api/controllers/location.js

Reverts cboard-org/cboard-api#344

Revert "Fix get location endpoint if the ip includes the port"

---

api/helpers/localize.js

Remove port from ip to get user location

---

api/helpers/cbuilder.js

Add cbuilderToCboardTilesAdapter
